module.exports = {
  react: {
    RectWidth: 90,
    fontX: 40,
    fontY: 21,
    fontColor: "#61DAFB",
    fontSize: 14,
    defaultText: "React",
  },
  vue: {
    RectWidth: 90,
    fontX: 45,
    fontY: 21,
    fontColor: "#41B883",
    fontSize: 14,
    defaultText: "Vue",
  },
  svelte: {
    RectWidth: 90,
    fontX: 45,
    fontY: 21,
    fontColor: "#FF5722",
    fontSize: 14,
    defaultText: "Vue",
  },
  typescript: {
    RectWidth: 108,
    fontX: 37,
    fontY: 21,
    fontColor: "#0288D1",
    fontSize: 13,
    defaultText: "TypeScript",
  },
  javascript: {
    RectWidth: 106,
    fontX: 37,
    fontY: 21,
    fontColor: "#ffca28",
    fontSize: 13,
    defaultText: "JavaScript",
  },
  html: {
    RectWidth: 90,
    fontX: 42,
    fontY: 21,
    fontColor: "#FC490B",
    fontSize: 14,
    defaultText: "HTML",
  },
  css: {
    RectWidth: 90,
    fontX: 45,
    fontY: 21,
    fontColor: "#2196F3",
    fontSize: 14,
    defaultText: "CSS",
  },
  graphql: {
    RectWidth: 101,
    fontX: 36,
    fontY: 21,
    fontColor: "#EC407A",
    fontSize: 14,
    defaultText: "GraphQL",
  },
}
